/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * inertia_100.c
 *
 * Code generation for function 'inertia_100'
 *
 */

/* Include files */
#include "inertia_100.h"
#include "rt_nonfinite.h"
#include "runge_kutta_4_data.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void inertia_100(const real_T q[6], real_T b_I[36])
{
  real_T I_tmp;
  real_T b_I_tmp;
  real_T b_t18_tmp;
  real_T b_t30_tmp;
  real_T b_t31_tmp;
  real_T b_t39_tmp;
  real_T b_t68_tmp;
  real_T b_t69_tmp;
  real_T c_I_tmp;
  real_T d;
  real_T d1;
  real_T d10;
  real_T d11;
  real_T d12;
  real_T d13;
  real_T d14;
  real_T d15;
  real_T d16;
  real_T d17;
  real_T d18;
  real_T d19;
  real_T d2;
  real_T d20;
  real_T d21;
  real_T d22;
  real_T d23;
  real_T d24;
  real_T d3;
  real_T d4;
  real_T d5;
  real_T d6;
  real_T d7;
  real_T d8;
  real_T d9;
  real_T d_I_tmp;
  real_T e_I_tmp;
  real_T f_I_tmp;
  real_T g_I_tmp;
  real_T h_I_tmp;
  real_T i_I_tmp;
  real_T j_I_tmp;
  real_T k_I_tmp;
  real_T l_I_tmp;
  real_T m_I_tmp;
  real_T n_I_tmp;
  real_T o_I_tmp;
  real_T p_I_tmp;
  real_T t10;
  real_T t11;
  real_T t12_tmp;
  real_T t13_tmp;
  real_T t14;
  real_T t15;
  real_T t18;
  real_T t18_tmp;
  real_T t18_tmp_tmp_tmp;
  real_T t19;
  real_T t19_tmp;
  real_T t19_tmp_tmp;
  real_T t21;
  real_T t21_tmp;
  real_T t22;
  real_T t22_tmp;
  real_T t22_tmp_tmp_tmp;
  real_T t23;
  real_T t23_tmp_tmp;
  real_T t24;
  real_T t24_tmp_tmp;
  real_T t25;
  real_T t26;
  real_T t26_tmp;
  real_T t27;
  real_T t27_tmp;
  real_T t29;
  real_T t2_tmp;
  real_T t30;
  real_T t30_tmp;
  real_T t31;
  real_T t31_tmp;
  real_T t31_tmp_tmp;
  real_T t33;
  real_T t33_tmp;
  real_T t34;
  real_T t34_tmp_tmp;
  real_T t35;
  real_T t36;
  real_T t39;
  real_T t39_tmp;
  real_T t39_tmp_tmp;
  real_T t3_tmp;
  real_T t40;
  real_T t40_tmp;
  real_T t40_tmp_tmp;
  real_T t43;
  real_T t44;
  real_T t46;
  real_T t46_tmp;
  real_T t47;
  real_T t49;
  real_T t4_tmp;
  real_T t50;
  real_T t51;
  real_T t51_tmp;
  real_T t52;
  real_T t52_tmp;
  real_T t53;
  real_T t54;
  real_T t59;
  real_T t5_tmp;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t65;
  real_T t66;
  real_T t68;
  real_T t68_tmp;
  real_T t68_tmp_tmp;
  real_T t69;
  real_T t69_tmp;
  real_T t69_tmp_tmp;
  real_T t6_tmp;
  real_T t70;
  real_T t71;
  real_T t7_tmp;
  real_T t8_tmp;
  real_T t9_tmp;
  int32_T i;

  /*  INERTIA - Inertia matrix for the Quantec Ultra SE 100 arm.  */
  /*  =========================================================================  */
  /*      */
  /*     I = inertia(rob,q)  */
  /*     I = rob.inertia(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables the function computes the  */
  /*     inertia Matrix of the robot.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     I:  [6x6] inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  memset(&b_I[0], 0, 36U * sizeof(real_T));

  /*  INERTIA_ROW_1 - Computation of the robot specific inertia matrix row for corresponding to joint 1 of 6.  */
  /*  =========================================================================  */
  /*      */
  /*     Irow = inertia_row_1(rob,q)  */
  /*     Irow = rob.inertia_row_1(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables this function computes the  */
  /*     inertia matrix row number 1 of 6 for Quantec Ultra SE 100.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     Irow:  [1x6] row of the robot inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  /*  Bugfix */
  /*   In some versions the symbolic toolbox writes the constant $pi$ in */
  /*   capital letters. This way autogenerated functions might not work properly. */
  /*   To fix this issue a local variable is introduced: */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     02-Mar-2021 15:05:21 */
  t2_tmp = muDoubleScalarCos(q[1]);
  t3_tmp = muDoubleScalarCos(q[2]);
  t4_tmp = muDoubleScalarCos(q[3]);
  t5_tmp = muDoubleScalarCos(q[4]);
  t6_tmp = muDoubleScalarSin(q[1]);
  t7_tmp = muDoubleScalarSin(q[2]);
  t8_tmp = muDoubleScalarSin(q[3]);
  t9_tmp = muDoubleScalarSin(q[4]);
  t10 = t2_tmp * t2_tmp;
  t11 = t3_tmp * t3_tmp;
  t12_tmp = t4_tmp * t4_tmp;
  t13_tmp = t5_tmp * t5_tmp;
  t18_tmp_tmp_tmp = t2_tmp * t3_tmp;
  t18_tmp = t18_tmp_tmp_tmp * t4_tmp;
  b_t18_tmp = t18_tmp * t5_tmp;
  t18 = b_t18_tmp * t8_tmp * t9_tmp * 0.00024;
  t19_tmp_tmp = t4_tmp * t5_tmp;
  t19_tmp = t19_tmp_tmp * t6_tmp * t7_tmp;
  t19 = t19_tmp * t8_tmp * t9_tmp * 0.00024;
  t21 = t18_tmp * 0.1046566;
  t22_tmp_tmp_tmp = t4_tmp * t6_tmp;
  t22_tmp = t22_tmp_tmp_tmp * t7_tmp;
  t22 = t22_tmp * 0.1046566;
  t23_tmp_tmp = t2_tmp * t7_tmp;
  t23 = t23_tmp_tmp * 0.75031128;
  t24_tmp_tmp = t3_tmp * t6_tmp;
  t24 = t24_tmp_tmp * 0.75031128;
  t26_tmp = t23_tmp_tmp * t8_tmp;
  t26 = t26_tmp * t9_tmp * 37.66134;
  t27_tmp = t24_tmp_tmp * t8_tmp;
  t27 = t27_tmp * t9_tmp * 37.66134;
  t30_tmp = t18_tmp_tmp_tmp * t8_tmp;
  b_t30_tmp = t30_tmp * t9_tmp;
  t30 = b_t30_tmp * 1.54411494;
  t31_tmp_tmp = t6_tmp * t7_tmp;
  t31_tmp = t31_tmp_tmp * t8_tmp;
  b_t31_tmp = t31_tmp * t9_tmp;
  t31 = b_t31_tmp * 1.54411494;
  t33_tmp = t18_tmp_tmp_tmp * t5_tmp;
  t33 = t33_tmp * 4.0E-6;
  t34_tmp_tmp = t5_tmp * t6_tmp * t7_tmp;
  t34 = t34_tmp_tmp * 4.0E-6;
  t39_tmp_tmp = t2_tmp * t4_tmp;
  t39_tmp = t39_tmp_tmp * t7_tmp;
  b_t39_tmp = t39_tmp * t9_tmp;
  t39 = b_t39_tmp * 4.0E-6;
  t40_tmp_tmp = t3_tmp * t4_tmp;
  t71 = t40_tmp_tmp * t6_tmp;
  t40_tmp = t71 * t9_tmp;
  t40 = t40_tmp * 4.0E-6;
  t46_tmp = t31_tmp_tmp * t9_tmp;
  t46 = t46_tmp * 0.0421722;
  t25 = t18_tmp_tmp_tmp * t9_tmp;
  t47 = t25 * 0.0421722;
  t49 = t26_tmp * 0.000116;
  t50 = t27_tmp * 0.000116;
  t51_tmp = t39_tmp_tmp * t5_tmp;
  t51 = t51_tmp * t7_tmp * 0.0421722;
  t52_tmp = t40_tmp_tmp * t5_tmp;
  t52 = t52_tmp * t6_tmp * 0.0421722;
  t53 = t39_tmp * 2.5327982;
  t54 = t71 * 2.5327982;
  t59 = t31_tmp_tmp * 0.16200394;
  t62 = t18_tmp_tmp_tmp * 0.16200394;
  t71 = t18_tmp * t8_tmp;
  t65 = t71 * 11.63809377431482;
  t29 = t22_tmp * t8_tmp;
  t66 = t29 * 11.63809377431482;
  t68_tmp_tmp = t2_tmp * t5_tmp;
  t68_tmp = t68_tmp_tmp * t7_tmp;
  b_t68_tmp = t68_tmp * t8_tmp;
  t68 = b_t68_tmp * t9_tmp * 11.89030757431482;
  t69_tmp_tmp = t3_tmp * t5_tmp;
  t69_tmp = t69_tmp_tmp * t6_tmp;
  b_t69_tmp = t69_tmp * t8_tmp;
  t69 = b_t69_tmp * t9_tmp * 11.89030757431482;
  t14 = t26_tmp * t13_tmp * 0.00024;
  t15 = t27_tmp * t13_tmp * 0.00024;
  t35 = t18_tmp_tmp_tmp * t12_tmp * 5.4E-5;
  t36 = t31_tmp_tmp * t12_tmp * 5.4E-5;
  t43 = t33_tmp * t12_tmp * 8.0E-6;
  t44 = t34_tmp_tmp * t12_tmp * 8.0E-6;
  t60 = t25 * t12_tmp * 0.0843444;
  t61 = t46_tmp * t12_tmp * 0.0843444;
  t70 = t71 * t13_tmp * 11.89030757431482;
  t71 = t29 * t13_tmp * 11.89030757431482;
  t25 = t5_tmp * t10;
  d = muDoubleScalarSin(q[3] * 2.0) * 2.7E-5;
  t29 = t8_tmp * t10;
  I_tmp = t2_tmp * t6_tmp;
  b_I_tmp = t3_tmp * t7_tmp;
  t39_tmp = t4_tmp * t8_tmp;
  t21_tmp = t4_tmp * t9_tmp;
  d1 = t5_tmp * t9_tmp;
  t46_tmp = t10 * t11;
  d2 = t10 * t12_tmp;
  d3 = t11 * t12_tmp;
  d4 = t18_tmp_tmp_tmp * t6_tmp;
  d5 = t68_tmp_tmp * t6_tmp;
  d6 = t39_tmp_tmp * t6_tmp;
  d7 = t40_tmp_tmp * t7_tmp;
  d8 = t69_tmp_tmp * t7_tmp;
  d9 = I_tmp * t8_tmp;
  d10 = b_I_tmp * t8_tmp;
  d11 = t19_tmp_tmp * t8_tmp;
  d12 = t39_tmp * t9_tmp;
  d13 = t39_tmp * t10;
  d14 = t21_tmp * t10;
  d15 = d1 * t10;
  d16 = d1 * t11;
  d17 = t46_tmp * t12_tmp;
  d18 = d4 * t7_tmp;
  d19 = d6 * t9_tmp;
  d20 = d5 * t8_tmp;
  d21 = d7 * t9_tmp;
  d22 = d6 * t11;
  d23 = d8 * t8_tmp;
  d24 = d7 * t10;
  c_I_tmp = d10 * t9_tmp;
  d_I_tmp = d11 * t10;
  e_I_tmp = d12 * t10;
  f_I_tmp = d15 * t11;
  g_I_tmp = t18_tmp * t6_tmp;
  h_I_tmp = g_I_tmp * t7_tmp;
  i_I_tmp = t33_tmp * t6_tmp * t7_tmp;
  j_I_tmp = t51_tmp * t6_tmp * t9_tmp;
  k_I_tmp = t52_tmp * t7_tmp * t9_tmp;
  l_I_tmp = d18 * t12_tmp;
  m_I_tmp = h_I_tmp * t8_tmp;
  n_I_tmp = i_I_tmp * t9_tmp;
  o_I_tmp = t7_tmp * t8_tmp;
  p_I_tmp = t4_tmp * t7_tmp * t9_tmp;
  b_I[0] =
    (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
    (((((((((((((((((((((((((((((((((((t2_tmp * 338.337594 + t5_tmp * 75.32268)
    + t6_tmp * 0.237384) + t10 * 352.01380597) - t11 * 179.17274863) - t12_tmp *
    11.63809377431482) + muDoubleScalarSin(q[1] * 2.0) * 7.9017942) +
    muDoubleScalarSin(q[2] * 2.0) * 7.32219628) - d) + t18_tmp_tmp_tmp *
    129.211012) - t23_tmp_tmp * 7.004529) - t24_tmp_tmp * 7.004529) + t3_tmp *
    t10 * 424.550468) - t31_tmp_tmp * 129.211012) - t25 * 75.32268) - t5_tmp *
    t11 * 75.32268) - t7_tmp * t10 * 23.014881) + t29 * 0.2093132) + t8_tmp *
    t11 * 0.2093132) + t46_tmp * 358.34549726) + d2 * 11.63809377431482) - t10 *
    t13_tmp * 11.89030757431482) + d3 * 11.63809377431482) - t11 * t13_tmp *
    11.89030757431482) + t12_tmp * t13_tmp * 11.89030757431482) + t33_tmp *
    26.362938) - d4 * 23.014881) + d6 * 0.000232) + d5 * 3.08822988) + d7 *
    0.000232) - I_tmp * t7_tmp * 424.550468) + d8 * 3.08822988) + d9 * 5.0655964)
    - t26_tmp * 1.78682) - t27_tmp * 1.78682) + d11 * 8.0E-6) + t69_tmp_tmp *
    t10 * 86.621082) + d10 * 5.0655964) - t34_tmp_tmp * 26.362938) - I_tmp * t11
    * 29.28878512) - b_I_tmp * t10 * 29.28878512) - d12 * 0.0843444) + d13 *
    5.4E-5) + t39_tmp * t11 * 5.4E-5) + d14 * 3.08822988) + t21_tmp * t11 *
    3.08822988) - d15 * 0.00024) - d16 * 0.00024) - o_I_tmp * t10 * 5.87098) +
    d1 * t12_tmp * 0.00024) + t25 * t11 * 150.64536) - t29 * t11 * 0.4186264) -
    d17 * 23.27618754862965) + t46_tmp * t13_tmp * 23.78061514862965) - d2 *
    t13_tmp * 11.89030757431482) - d3 * t13_tmp * 11.89030757431482) - d18 *
    358.34549726) - d4 * t8_tmp * 5.87098) - d5 * t7_tmp * 86.621082) + d19 *
    75.32268) + d20 * 0.0843444) - b_t39_tmp * 26.362938) - t40_tmp * 26.362938)
    - d22 * 0.000464) + d21 * 75.32268) + d23 * 0.0843444) - d5 * t11 *
    6.17645976) - d24 * 0.000464) - d6 * t13_tmp * 0.00048) + d9 * t9_tmp *
    8.0E-6) - d8 * t10 * 6.17645976) - d9 * t11 * 10.1311928) - t3_tmp * t4_tmp *
    t7_tmp * t13_tmp * 0.00048) + c_I_tmp * 8.0E-6) - d_I_tmp * 8.0E-6) - d10 *
    t10 * 10.1311928) - d11 * t11 * 8.0E-6) - p_I_tmp * t10 * 86.621082) +
    e_I_tmp * 0.0843444) + d12 * t11 * 0.0843444) - d13 * t11 * 0.000108) - d14 *
    t11 * 6.17645976) + f_I_tmp * 0.00048) - d15 * t12_tmp * 0.00024) - d16 *
    t12_tmp * 0.00024) + d17 * t13_tmp * 23.78061514862965) - i_I_tmp *
    150.64536) - g_I_tmp * t9_tmp * 86.621082) + d18 * t8_tmp * 0.4186264) +
    j_I_tmp * 23.78061514862965) + k_I_tmp * 23.78061514862965) + l_I_tmp *
    23.27618754862965) - d18 * t13_tmp * 23.78061514862965) - d19 * t11 *
    150.64536) - d20 * t11 * 0.1686888) - d21 * t10 * 150.64536) - d23 * t10 *
                     0.1686888) + d22 * t13_tmp * 0.00096) - t2_tmp * t6_tmp *
                   t8_tmp * t9_tmp * t11 * 1.6E-5) + d24 * t13_tmp * 0.00096) -
                 c_I_tmp * t10 * 1.6E-5) + d_I_tmp * t11 * 1.6E-5) - e_I_tmp *
               t11 * 0.1686888) + f_I_tmp * t12_tmp * 0.00048) + m_I_tmp *
             0.000108) + h_I_tmp * t9_tmp * 6.17645976) - n_I_tmp * 0.00048) -
          j_I_tmp * t11 * 47.5612302972593) - k_I_tmp * t10 * 47.5612302972593)
        - l_I_tmp * t13_tmp * 23.78061514862965) - b_t18_tmp * t6_tmp * t7_tmp *
       t8_tmp * 1.6E-5) + m_I_tmp * t9_tmp * 0.1686888) - n_I_tmp * t12_tmp *
     0.00048) + 926.799160867376;
  c_I_tmp = t2_tmp * 0.11686308 + t6_tmp * 18.25116472;
  d_I_tmp = t6_tmp * t8_tmp * t9_tmp * 43.310541;
  b_I[6] = (((((((((((((((((((((((((((((((((((((((c_I_tmp + -t14) + -t15) + t19)
    + -t18) + t22) + -t21) + t26) + t27) + -t23) + -t24) + t30) + -t31) + t34) +
    t36) + -t33) + -t35) + -t39) + -t40) + t43) + -t44) + t47) + -t46) + t49) +
    t50) + -t51) + -t52) + -t53) + -t54) + t59) + t61) + -t60) + -t62) + t65) +
                 -t66) + t68) + t69) + t71) + -t70) - t22_tmp_tmp_tmp * 2.93549)
    + d_I_tmp;
  b_I[12] = ((((((((((((((((((((((((((((((((((((-t14 + -t15) + t19) + -t18) +
    t22) + -t21) + t26) + t27) + -t23) + -t24) + t30) + -t31) + t34) + t36) +
    -t33) + -t35) + -t39) + -t40) + t43) + -t44) + t47) + -t46) + t49) + t50) +
    -t51) + -t52) + -t53) + -t54) + t59) + t61) + -t60) + -t62) + t65) + -t66) +
               t68) + t69) + t71) + -t70;
  e_I_tmp = t18_tmp * t9_tmp;
  f_I_tmp = t33_tmp * t8_tmp;
  g_I_tmp = t34_tmp_tmp * t8_tmp;
  h_I_tmp = t2_tmp * t8_tmp * 2.93549;
  b_I[18] = ((((((((((((((((((((((((((t8_tmp * 0.89341 - t23_tmp_tmp *
    12.56794637431482) - t24_tmp_tmp * 12.56794637431482) + h_I_tmp) + t21_tmp *
    13.181469) + t18_tmp * 0.000116) + t30_tmp * 2.5327982) + t39_tmp_tmp *
    t9_tmp * 43.310541) - t26_tmp * 0.1046566) - t27_tmp * 0.1046566) - t22_tmp *
    0.000116) - t31_tmp * 2.5327982) + t23_tmp_tmp * t13_tmp * 11.89030757431482)
    + t24_tmp_tmp * t13_tmp * 11.89030757431482) + e_I_tmp * 37.66134) + f_I_tmp
                        * 0.0421722) - t18_tmp * t13_tmp * 0.00024) + b_t30_tmp *
                      4.0E-6) - b_t39_tmp * 1.54411494) - t40_tmp * 1.54411494)
                   + t68_tmp * t9_tmp * 0.00024) + t69_tmp * t9_tmp * 0.00024) -
                 t22_tmp * t9_tmp * 37.66134) - g_I_tmp * 0.0421722) + t22_tmp *
               t13_tmp * 0.00024) - b_t31_tmp * 4.0E-6) + b_t18_tmp * t9_tmp *
             11.89030757431482) - t19_tmp * t9_tmp * 11.89030757431482;
  i_I_tmp = t5_tmp * t8_tmp;
  b_I[24] = ((((((((((((((i_I_tmp * 13.181469 + t4_tmp * t33) + t4_tmp * t46) +
                        t30_tmp * 12.094309574314821) - t68_tmp * 0.0421722) -
                      t69_tmp * 0.0421722) + t68_tmp_tmp * t8_tmp * 43.310541) -
                    t23_tmp_tmp * t9_tmp * 4.0E-6) - t24_tmp_tmp * t9_tmp *
                   4.0E-6) - t31_tmp * 12.094309574314821) - e_I_tmp * 0.0421722)
                + f_I_tmp * 37.66134) - b_t68_tmp * 1.54411494) - b_t69_tmp *
              1.54411494) - t19_tmp * 4.0E-6) - g_I_tmp * 37.66134;
  b_I[30] = 0.0;

  /*  INERTIA_ROW_2 - Computation of the robot specific inertia matrix row for corresponding to joint 2 of 6.  */
  /*  =========================================================================  */
  /*      */
  /*     Irow = inertia_row_2(rob,q)  */
  /*     Irow = rob.inertia_row_2(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables this function computes the  */
  /*     inertia matrix row number 2 of 6 for Quantec Ultra SE 100.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     Irow:  [1x6] row of the robot inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  /*  Bugfix */
  /*   In some versions the symbolic toolbox writes the constant $pi$ in */
  /*   capital letters. This way autogenerated functions might not work properly. */
  /*   To fix this issue a local variable is introduced: */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     02-Mar-2021 15:05:22 */
  t71 = t5_tmp * 75.32268;
  t19_tmp = t8_tmp * 0.2093132;
  t21 = t21_tmp * 3.08822988;
  t23 = t19_tmp_tmp * t8_tmp * 8.0E-6;
  t25 = t4_tmp * t8_tmp * t9_tmp * 0.0843444;
  t46_tmp = muDoubleScalarSin(q[4] * 2.0) * 0.00012;
  t18 = d1 * t12_tmp * 0.00024;
  t26 = t12_tmp * 11.63809377431482;
  t27 = t13_tmp * 11.89030757431482;
  t29 = t12_tmp * t13_tmp * -11.89030757431482;
  e_I_tmp = t18_tmp_tmp_tmp * t4_tmp;
  f_I_tmp = t18_tmp_tmp_tmp * t5_tmp;
  g_I_tmp = t39_tmp_tmp * t7_tmp;
  j_I_tmp = t40_tmp_tmp * t6_tmp;
  k_I_tmp = t22_tmp_tmp_tmp * t7_tmp;
  l_I_tmp = t18_tmp_tmp_tmp * t9_tmp;
  m_I_tmp = t23_tmp_tmp * t8_tmp;
  n_I_tmp = t24_tmp_tmp * t8_tmp;
  t51_tmp = t31_tmp_tmp * t9_tmp;
  t52_tmp = e_I_tmp * t8_tmp;
  I_tmp = k_I_tmp * t8_tmp;
  b_I_tmp = t40_tmp_tmp * t5_tmp;
  b_I[1] = (((((((((((((((((((((((((((((((((((((((c_I_tmp - t18_tmp_tmp_tmp *
    0.16200394) - t23_tmp_tmp * 0.75031128) - t24_tmp_tmp * 0.75031128) -
    t22_tmp_tmp_tmp * 2.93549) + t31_tmp_tmp * 0.16200394) - e_I_tmp * 0.1046566)
    - f_I_tmp * 4.0E-6) - g_I_tmp * 2.5327982) - j_I_tmp * 2.5327982) + l_I_tmp *
    0.0421722) - t18_tmp_tmp_tmp * t12_tmp * 5.4E-5) + m_I_tmp * 0.000116) +
    n_I_tmp * 0.000116) + k_I_tmp * 0.1046566) + t34_tmp_tmp * 4.0E-6) - t51_tmp
    * 0.0421722) + d_I_tmp) + t31_tmp_tmp * t12_tmp * 5.4E-5) + t52_tmp *
    11.63809377431482) - t39_tmp_tmp * t5_tmp * t7_tmp * 0.0421722) - b_I_tmp *
    t6_tmp * 0.0421722) + f_I_tmp * t12_tmp * 8.0E-6) + t18_tmp_tmp_tmp * t8_tmp
    * t9_tmp * 1.54411494) - g_I_tmp * t9_tmp * 4.0E-6) - j_I_tmp * t9_tmp *
    4.0E-6) - I_tmp * 11.63809377431482) - l_I_tmp * t12_tmp * 0.0843444) +
                       m_I_tmp * t9_tmp * 37.66134) + n_I_tmp * t9_tmp *
                      37.66134) - m_I_tmp * t13_tmp * 0.00024) - n_I_tmp *
                    t13_tmp * 0.00024) - t34_tmp_tmp * t12_tmp * 8.0E-6) -
                  t31_tmp_tmp * t8_tmp * t9_tmp * 1.54411494) + t51_tmp *
                 t12_tmp * 0.0843444) - t52_tmp * t13_tmp * 11.89030757431482) +
               t2_tmp * t5_tmp * t7_tmp * t8_tmp * t9_tmp * 11.89030757431482) +
              t69_tmp_tmp * t6_tmp * t8_tmp * t9_tmp * 11.89030757431482) +
             I_tmp * t27) - e_I_tmp * t5_tmp * t8_tmp * t9_tmp * 0.00024) +
    t19_tmp_tmp * t6_tmp * t7_tmp * t8_tmp * t9_tmp * 0.00024;
  b_I[7] = (((((((((((((((t3_tmp * 424.550468 - t7_tmp * 23.014881) + t46_tmp) +
                        t71) + t19_tmp) + -t18) + t21) + d) + -t23) + t25) + t26)
                + t27) + t29) + t69_tmp_tmp * 86.621082) - o_I_tmp * 5.87098) -
            p_I_tmp * 86.621082) + 1564.576537362653;
  c_I_tmp = (t3_tmp * 212.275234 - t7_tmp * 11.5074405) + t46_tmp;
  b_I[13] = (((((((((((((c_I_tmp + t71) + t19_tmp) + -t18) + t21) + d) + -t23) +
                   t25) + t26) + t27) + t29) + t69_tmp_tmp * 43.310541) -
              o_I_tmp * 2.93549) - p_I_tmp * 43.310541) + 182.18153389;
  t39_tmp = t8_tmp * t9_tmp;
  d_I_tmp = t4_tmp * 2.5327982 - t8_tmp * 0.000116;
  e_I_tmp = t3_tmp * t8_tmp * t9_tmp * 43.310541;
  b_I[19] = ((((((d_I_tmp + t40_tmp_tmp * 2.93549) + t19_tmp_tmp * 0.0421722) +
                t21_tmp * 4.0E-6) - t39_tmp * 37.66134) + t8_tmp * t13_tmp *
              0.00024) - e_I_tmp) - i_I_tmp * t9_tmp * 11.89030757431482;
  f_I_tmp = t4_tmp * 12.094309574314821 + t9_tmp * 1.54411494;
  g_I_tmp = t7_tmp * t9_tmp * 43.310541;
  b_I[25] = ((((f_I_tmp + t19_tmp_tmp * 37.66134) - i_I_tmp * 4.0E-6) - g_I_tmp)
             + t39_tmp * 0.0421722) + b_I_tmp * 43.310541;
  b_I[31] = 0.0;

  /*  INERTIA_ROW_3 - Computation of the robot specific inertia matrix row for corresponding to joint 3 of 6.  */
  /*  =========================================================================  */
  /*      */
  /*     Irow = inertia_row_3(rob,q)  */
  /*     Irow = rob.inertia_row_3(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables this function computes the  */
  /*     inertia matrix row number 3 of 6 for Quantec Ultra SE 100.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     Irow:  [1x6] row of the robot inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  /*  Bugfix */
  /*   In some versions the symbolic toolbox writes the constant $pi$ in */
  /*   capital letters. This way autogenerated functions might not work properly. */
  /*   To fix this issue a local variable is introduced: */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     02-Mar-2021 15:05:22 */
  t71 = t5_tmp * 75.32268;
  t21 = t21_tmp * 3.08822988;
  t23 = t19_tmp_tmp * t8_tmp * 8.0E-6;
  t25 = t4_tmp * t8_tmp * t9_tmp * 0.0843444;
  t18 = d1 * t12_tmp * 0.00024;
  t26 = t12_tmp * 11.63809377431482;
  t27 = t13_tmp * 11.89030757431482;
  t29 = t12_tmp * t13_tmp * -11.89030757431482;
  j_I_tmp = t18_tmp_tmp_tmp * t4_tmp;
  k_I_tmp = t18_tmp_tmp_tmp * t5_tmp;
  l_I_tmp = t39_tmp_tmp * t7_tmp;
  m_I_tmp = t40_tmp_tmp * t6_tmp;
  n_I_tmp = t4_tmp * t6_tmp * t7_tmp;
  o_I_tmp = t18_tmp_tmp_tmp * t9_tmp;
  p_I_tmp = t23_tmp_tmp * t8_tmp;
  t51_tmp = t24_tmp_tmp * t8_tmp;
  t52_tmp = t31_tmp_tmp * t9_tmp;
  I_tmp = j_I_tmp * t8_tmp;
  b_I_tmp = n_I_tmp * t8_tmp;
  b_I[2] = ((((((((((((((((((((((((((((((((((((t18_tmp_tmp_tmp * -0.16200394 -
    t23_tmp_tmp * 0.75031128) - t24_tmp_tmp * 0.75031128) + t31_tmp_tmp *
    0.16200394) - j_I_tmp * 0.1046566) - k_I_tmp * 4.0E-6) - l_I_tmp * 2.5327982)
    - m_I_tmp * 2.5327982) + o_I_tmp * 0.0421722) - t18_tmp_tmp_tmp * t12_tmp *
    5.4E-5) + p_I_tmp * 0.000116) + t51_tmp * 0.000116) + n_I_tmp * 0.1046566) +
    t34_tmp_tmp * 4.0E-6) - t52_tmp * 0.0421722) + t31_tmp_tmp * t12_tmp *
    5.4E-5) + I_tmp * 11.63809377431482) - t39_tmp_tmp * t5_tmp * t7_tmp *
    0.0421722) - t40_tmp_tmp * t5_tmp * t6_tmp * 0.0421722) + k_I_tmp * t12_tmp *
    8.0E-6) + t18_tmp_tmp_tmp * t8_tmp * t9_tmp * 1.54411494) - l_I_tmp * t9_tmp
    * 4.0E-6) - m_I_tmp * t9_tmp * 4.0E-6) - b_I_tmp * 11.63809377431482) -
                        o_I_tmp * t12_tmp * 0.0843444) + p_I_tmp * t9_tmp *
                       37.66134) + t51_tmp * t9_tmp * 37.66134) - p_I_tmp *
                     t13_tmp * 0.00024) - t51_tmp * t13_tmp * 0.00024) -
                   t34_tmp_tmp * t12_tmp * 8.0E-6) - t31_tmp_tmp * t8_tmp *
                  t9_tmp * 1.54411494) + t52_tmp * t12_tmp * 0.0843444) - I_tmp *
                t13_tmp * 11.89030757431482) + t2_tmp * t5_tmp * t7_tmp * t8_tmp
               * t9_tmp * 11.89030757431482) + t69_tmp_tmp * t6_tmp * t8_tmp *
              t9_tmp * 11.89030757431482) + b_I_tmp * t27) - j_I_tmp * t5_tmp *
            t8_tmp * t9_tmp * 0.00024) + t19_tmp_tmp * t6_tmp * t7_tmp * t8_tmp *
    t9_tmp * 0.00024;
  b_I[8] = (((((((((((((c_I_tmp + t71) + t19_tmp) + -t18) + t21) + d) + -t23) +
                  t25) + t26) + t27) + t29) + t69_tmp_tmp * 43.310541) - t7_tmp *
             t8_tmp * 2.93549) - t4_tmp * t7_tmp * t9_tmp * 43.310541) +
    182.18153389;
  b_I[14] = ((((((((((t46_tmp + t71) + t19_tmp) + -t18) + t21) + d) + -t23) +
                t25) + t26) + t27) + t29) + 933.51244500111113;
  b_I[20] = ((((d_I_tmp + t19_tmp_tmp * 0.0421722) + t21_tmp * 4.0E-6) - t39_tmp
              * 37.66134) + t8_tmp * t13_tmp * 0.00024) - i_I_tmp * t9_tmp *
    11.89030757431482;
  b_I[26] = ((f_I_tmp + t19_tmp_tmp * 37.66134) - i_I_tmp * 4.0E-6) + t39_tmp *
    0.0421722;
  b_I[32] = 0.0;

  /*  INERTIA_ROW_4 - Computation of the robot specific inertia matrix row for corresponding to joint 4 of 6.  */
  /*  =========================================================================  */
  /*      */
  /*     Irow = inertia_row_4(rob,q)  */
  /*     Irow = rob.inertia_row_4(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables this function computes the  */
  /*     inertia matrix row number 4 of 6 for Quantec Ultra SE 100.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     Irow:  [1x6] row of the robot inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  /*  Bugfix */
  /*   In some versions the symbolic toolbox writes the constant $pi$ in */
  /*   capital letters. This way autogenerated functions might not work properly. */
  /*   To fix this issue a local variable is introduced: */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     02-Mar-2021 15:05:22 */
  c_I_tmp = t18_tmp_tmp_tmp * t4_tmp;
  d_I_tmp = t18_tmp_tmp_tmp * t8_tmp;
  f_I_tmp = t4_tmp * t6_tmp * t7_tmp;
  j_I_tmp = t6_tmp * t7_tmp * t8_tmp;
  b_I[3] = ((((((((((((((((((((((((((t8_tmp * 0.89341 - t23_tmp_tmp *
    12.56794637431482) - t24_tmp_tmp * 12.56794637431482) + h_I_tmp) + t21_tmp *
    13.181469) + c_I_tmp * 0.000116) + d_I_tmp * 2.5327982) + t39_tmp_tmp *
    t9_tmp * 43.310541) - t23_tmp_tmp * t8_tmp * 0.1046566) - t24_tmp_tmp *
    t8_tmp * 0.1046566) - f_I_tmp * 0.000116) + t23_tmp_tmp * t13_tmp *
    11.89030757431482) + t24_tmp_tmp * t13_tmp * 11.89030757431482) - j_I_tmp *
    2.5327982) + c_I_tmp * t9_tmp * 37.66134) + t18_tmp_tmp_tmp * t5_tmp *
                       t8_tmp * 0.0421722) - c_I_tmp * t13_tmp * 0.00024) +
                     d_I_tmp * t9_tmp * 4.0E-6) - t39_tmp_tmp * t7_tmp * t9_tmp *
                    1.54411494) - t40_tmp_tmp * t6_tmp * t9_tmp * 1.54411494) +
                  t2_tmp * t5_tmp * t7_tmp * t9_tmp * 0.00024) + t3_tmp * t5_tmp
                 * t6_tmp * t9_tmp * 0.00024) - f_I_tmp * t9_tmp * 37.66134) -
               t5_tmp * t6_tmp * t7_tmp * t8_tmp * 0.0421722) + f_I_tmp *
              t13_tmp * 0.00024) - j_I_tmp * t9_tmp * 4.0E-6) + c_I_tmp * t5_tmp
            * t9_tmp * 11.89030757431482) - t19_tmp_tmp * t6_tmp * t7_tmp *
    t9_tmp * 11.89030757431482;
  c_I_tmp = (((((t8_tmp * t13_tmp * 0.00024 + -(t8_tmp * t9_tmp * 37.66134)) +
                t21_tmp * 4.0E-6) + t19_tmp_tmp * 0.0421722) + t4_tmp *
              2.5327982) + -(t8_tmp * 0.000116)) + -(t5_tmp * t8_tmp * t9_tmp *
    11.89030757431482);
  b_I[9] = (c_I_tmp + t40_tmp_tmp * 2.93549) - e_I_tmp;
  b_I[15] = c_I_tmp;
  b_I[21] = (t13_tmp * -11.89030757431482 - t46_tmp) + 97.062876374314826;
  c_I_tmp = t5_tmp * 0.0421722 + t9_tmp * 4.0E-6;
  b_I[27] = c_I_tmp;
  b_I[33] = 0.0;

  /*  INERTIA_ROW_5 - Computation of the robot specific inertia matrix row for corresponding to joint 5 of 6.  */
  /*  =========================================================================  */
  /*      */
  /*     Irow = inertia_row_5(rob,q)  */
  /*     Irow = rob.inertia_row_5(q)  */
  /*      */
  /*   Description::  */
  /*     Given a full set of joint variables this function computes the  */
  /*     inertia matrix row number 5 of 6 for Quantec Ultra SE 100.  */
  /*      */
  /*   Input::  */
  /*     rob: robot object of Quantec Ultra SE 100 specific class  */
  /*     q:  6-element vector of generalized  */
  /*          coordinates  */
  /*     Angles have to be given in radians!  */
  /*      */
  /*   Output::  */
  /*     Irow:  [1x6] row of the robot inertia matrix  */
  /*      */
  /*   Example::  */
  /*     ---  */
  /*      */
  /*   Known Bugs::  */
  /*     ---  */
  /*      */
  /*   TODO::  */
  /*     ---  */
  /*      */
  /*   References::  */
  /*     1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar  */
  /*     2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano  */
  /*     3) Introduction to Robotics, Mechanics and Control - Craig  */
  /*     4) Modeling, Identification & Control of Robots - Khalil & Dombre  */
  /*      */
  /*   Authors::  */
  /*     This is an autogenerated function!  */
  /*     Code generator written by:  */
  /*     Joern Malzahn  */
  /*     2012 RST, Technische Universitaet Dortmund, Germany  */
  /*     http://www.rst.e-technik.tu-dortmund.de  */
  /*      */
  /*   See also coriolis. */
  /*      */
  /*  Copyright (C) 1993-2021, by Peter I. Corke  */
  /*  Copyright (C) 2012-2021, by Joern Malzahn  */
  /*   */
  /*  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB).  */
  /*   */
  /*  RTB and code generated with RTB is free software: you can redistribute it and/or modify  */
  /*  it under the terms of the GNU Lesser General Public License as published by  */
  /*  the Free Software Foundation, either version 3 of the License, or  */
  /*  (at your option) any later version.  */
  /*    */
  /*  RTB is distributed in the hope that it will be useful,  */
  /*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
  /*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  */
  /*  GNU Lesser General Public License for more details.  */
  /*    */
  /*  You should have received a copy of the GNU Leser General Public License  */
  /*  along with RTB.  If not, see <http://www.gnu.org/licenses/>.  */
  /*   */
  /*  http://www.petercorke.com  */
  /*   */
  /*  The code generation module emerged during the work on a project funded by  */
  /*  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully   */
  /*  acknowledge the financial support.  */
  /*  Bugfix */
  /*   In some versions the symbolic toolbox writes the constant $pi$ in */
  /*   capital letters. This way autogenerated functions might not work properly. */
  /*   To fix this issue a local variable is introduced: */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     02-Mar-2021 15:05:23 */
  d_I_tmp = t18_tmp_tmp_tmp * t4_tmp;
  e_I_tmp = t68_tmp_tmp * t7_tmp;
  f_I_tmp = t3_tmp * t5_tmp * t6_tmp;
  b_I[4] = ((((((((((((((i_I_tmp * 13.181469 + t18_tmp_tmp_tmp * t8_tmp *
    12.094309574314821) - e_I_tmp * 0.0421722) - f_I_tmp * 0.0421722) +
                      t68_tmp_tmp * t8_tmp * 43.310541) - t2_tmp * t7_tmp *
                     t9_tmp * 4.0E-6) - t3_tmp * t6_tmp * t9_tmp * 4.0E-6) -
                   t6_tmp * t7_tmp * t8_tmp * 12.094309574314821) + d_I_tmp *
                  t5_tmp * 4.0E-6) - d_I_tmp * t9_tmp * 0.0421722) +
                t18_tmp_tmp_tmp * t5_tmp * t8_tmp * 37.66134) - e_I_tmp * t8_tmp
               * 1.54411494) - f_I_tmp * t8_tmp * 1.54411494) - t19_tmp_tmp *
             t6_tmp * t7_tmp * 4.0E-6) + t4_tmp * t6_tmp * t7_tmp * t9_tmp *
            0.0421722) - t5_tmp * t6_tmp * t7_tmp * t8_tmp * 37.66134;
  d_I_tmp = (((t19_tmp_tmp * 37.66134 + t9_tmp * 1.54411494) + -(i_I_tmp *
    4.0E-6)) + t8_tmp * t9_tmp * 0.0421722) + t4_tmp * 12.094309574314821;
  b_I[10] = (d_I_tmp - g_I_tmp) + t3_tmp * t4_tmp * t5_tmp * 43.310541;
  b_I[16] = d_I_tmp;
  b_I[22] = c_I_tmp;
  b_I[28] = 111.4262177829316;
  b_I[34] = 0.0;
  for (i = 0; i < 6; i++) {
    b_I[6 * i + 5] = dv[i];
  }
}

/* End of code generation (inertia_100.c) */
